name: Deploy .NET API to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x 

      - name: Restaurar dependências
        run: dotnet restore BitFolio.csproj

      - name: Compilar e publicar
        run: dotnet publish BitFolio.csproj -c Release -o ./publish

      - name: Criar deploy.zip
        run: |
          cd publish
          zip -r ../deploy.zip .

      - name: Upload deploy.zip para S3
        run: aws s3 cp deploy.zip s3://${{ secrets.EB_S3_BUCKET }}/deploy.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Criar versão e atualizar Beanstalk
        run: |
          VERSION_LABEL=v-${{ github.run_number }}-${{ github.sha }}

          aws elasticbeanstalk create-application-version \
            --application-name ${{ secrets.EB_APP_NAME }} \
            --version-label $VERSION_LABEL \
            --source-bundle S3Bucket=${{ secrets.EB_S3_BUCKET }},S3Key=deploy.zip

          aws elasticbeanstalk update-environment \
            --environment-name ${{ secrets.EB_ENV_NAME }} \
            --version-label $VERSION_LABEL
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          DOTNET_ROOT: /usr/share/dotnet
          